# Generated by Django 5.0.3 on 2024-03-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('Nebulosa', 'NEBULOSA'), ('Estrela', 'ESTRELA'), ('Galáxia', 'GALÁXIA'), ('Planeta', 'PLANETA')], default='', max_length=100),
        ),
    ]
